name: 06 B passing values between jobs

on:
  workflow_dispatch:

jobs:
  data-sender:
    runs-on: ubuntu-latest

    steps:
      - name: Data sender
        id: data-sender
        run: echo "name=Martin" >> $GITHUB_OUTPUT
    
    outputs:
      name: ${{ steps.data-sender.outputs.name }}

  data-receiver:
    runs-on: ubuntu-latest
    needs:
      - data-sender
    
    steps:
      - name: Data receiver
        run: echo ${{ needs.data-sender.outputs.name }}