name: 08 Secrets and variables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_ENV: 'production'
    
    steps:
      - name: Build
        run: |
          echo "Building the application"
          echo ${{ secrets.API_KEY }}
          echo ${{ env.DEPLOYMENT_ENV }}
          echo $SECRET_API_KEY
          echo $CONFIG_VARIABLE
          echo #STEPS_USERNAME
          echo ${{ vars.username }}

        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
          STEPS_USERNAME: ${{ vars.username }}
          CONFIG_VARIABLE: ${{ env.DEPLOYMENT_ENV }}

      - name: Deploy
        run: |
          echo "Global job variable ${{ env.DEPLOYMENT_ENV }}"
          echo "Variable from previous step ${CONFIG_VARIABLE} environment"
          echo "Variable from this step ${CONFIG_VARIABLE2} environment"
          echo "Local step variable ${ANOTHER_VARIABLE}"
          echo "Secret print ${{ secrets.API_KEY }}"
          echo "Step's secret variable ${SECRET_API_KEY}"

        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
          CONFIG_VARIABLE2: ${{ env.DEPLOYMENT_ENV }}
          ANOTHER_VARIABLE: 'some value anpther'