name: 08 Secrets and variables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_ENV: 'production'
    
    steps:
      - name: Build
        run: |
          echo "Building the application"
          echo ${{ secrets.API_KEY }} // undefined
          echo ${{ env.DEPLOYMENT_ENV }} // production
          echo $SECRET_API_KEY // undefined
          echo $CONFIG_VARIABLE // production
          echo #STEPS_USERNAME // Martinko
          echo ${{ vars.USERNAME }} // Martinko

        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
          STEPS_USERNAME: ${{ vars.USERNAME }}
          CONFIG_VARIABLE: ${{ env.DEPLOYMENT_ENV }}

      - name: Deploy
        run: |
          echo "Global job variable ${{ env.DEPLOYMENT_ENV }}" //production
          echo "Variable from previous step ${CONFIG_VARIABLE} environment" // undefined
          echo "Variable from this step ${CONFIG_VARIABLE2} environment" // production
          echo "Local step variable ${ANOTHER_VARIABLE}" // some value another
          echo "Secret print ${{ secrets.API_KEY }}" // undefined
          echo "Step's secret variable ${SECRET_API_KEY}" // undefined

        env:
          SECRET_API_KEY: ${{ secrets.API_KEY }}
          CONFIG_VARIABLE2: ${{ env.DEPLOYMENT_ENV }}
          ANOTHER_VARIABLE: 'some value anpther'